#Requires -Version 5.1
<#
.SYNOPSIS
    Pixelfy one-click build script for Windows PowerShell.
.DESCRIPTION
    Detects your JDK and Android SDK, sets everything up, builds the debug APK.
    Usage: .\build.ps1
#>

$ErrorActionPreference = "Continue"

Write-Host ""
Write-Host "  ========================================" -ForegroundColor Cyan
Write-Host "     Pixelfy Build Script" -ForegroundColor Cyan
Write-Host "  ========================================" -ForegroundColor Cyan
Write-Host ""

# --- Step 1: Check JDK ---
Write-Host "[1/4] Checking Java..." -ForegroundColor Yellow

$javaExe = $null
$javaHome = $null

# Try PATH first
$javaOnPath = Get-Command java -ErrorAction SilentlyContinue
if ($javaOnPath) {
    $javaExe = $javaOnPath.Source
}

# If not on PATH, search common install locations
if (-not $javaExe) {
    $searchDirs = @(
        "C:\Program Files\Microsoft\jdk-*",
        "C:\Program Files\Eclipse Adoptium\jdk-*",
        "C:\Program Files\Java\jdk-*",
        "C:\Program Files\Zulu\zulu-*",
        "C:\Program Files\Amazon Corretto\jdk*",
        "$env:LOCALAPPDATA\Programs\Android\Android Studio\jbr",
        "$env:LOCALAPPDATA\Programs\Android\Android Studio\jre"
    )
    foreach ($pattern in $searchDirs) {
        $found = Get-ChildItem -Path $pattern -Directory -ErrorAction SilentlyContinue |
            Sort-Object Name -Descending |
            Select-Object -First 1
        if ($found -and (Test-Path "$($found.FullName)\bin\java.exe")) {
            $javaExe = "$($found.FullName)\bin\java.exe"
            $javaHome = $found.FullName
            break
        }
    }
}

if (-not $javaExe) {
    Write-Host "  ERROR: Java not found anywhere!" -ForegroundColor Red
    Write-Host "  Install JDK 21+ from: https://aka.ms/download-jdk/microsoft-jdk-21.0.7-windows-x64.msi" -ForegroundColor Red
    Write-Host "  Then restart PowerShell and try again." -ForegroundColor Red
    exit 1
}

# Set JAVA_HOME if we found it manually
if ($javaHome) {
    $env:JAVA_HOME = $javaHome
    $env:PATH = "$javaHome\bin;$env:PATH"
}

$prevEAP = $ErrorActionPreference
$ErrorActionPreference = "Continue"
$javaVersion = & $javaExe -version 2>&1 | Select-Object -First 1
$ErrorActionPreference = $prevEAP
Write-Host "  Found: $javaVersion" -ForegroundColor Green

# Extract major version number
$versionString = ($javaVersion.ToString() -replace '.*version "(\d+).*', '$1')
$majorVersion = [int]$versionString
if ($majorVersion -lt 21) {
    Write-Host "  ERROR: Java 21+ required (you have $majorVersion)" -ForegroundColor Red
    Write-Host "  Install from: https://aka.ms/download-jdk/microsoft-jdk-21.0.7-windows-x64.msi" -ForegroundColor Red
    exit 1
}
Write-Host "  Java $majorVersion >= 21 OK" -ForegroundColor Green

# --- Step 2: Find Android SDK ---
Write-Host ""
Write-Host "[2/4] Finding Android SDK..." -ForegroundColor Yellow

$sdkPath = $null
$searchPaths = @(
    "$env:LOCALAPPDATA\Android\Sdk",
    "$env:USERPROFILE\AppData\Local\Android\Sdk",
    "C:\Android\Sdk",
    "$env:ANDROID_HOME",
    "$env:ANDROID_SDK_ROOT"
) | Where-Object { $_ -and $_ -ne "" }

foreach ($path in $searchPaths) {
    if (Test-Path "$path\platforms") {
        $sdkPath = $path
        break
    }
}

if (-not $sdkPath) {
    Write-Host "  ERROR: Android SDK not found!" -ForegroundColor Red
    Write-Host "  Searched:" -ForegroundColor Red
    $searchPaths | ForEach-Object { Write-Host "    - $_" -ForegroundColor Red }
    Write-Host ""
    Write-Host "  Install Android Studio: https://developer.android.com/studio" -ForegroundColor Red
    Write-Host "  Or set ANDROID_HOME to your SDK path." -ForegroundColor Red
    exit 1
}

Write-Host "  SDK found: $sdkPath" -ForegroundColor Green

# --- Step 3: Create local.properties ---
Write-Host ""
Write-Host "[3/4] Configuring project..." -ForegroundColor Yellow

$localProps = Join-Path $PSScriptRoot "local.properties"
$sdkEscaped = $sdkPath -replace '\\', '\\\\'
$propsContent = @"
# Auto-generated by build.ps1
sdk.dir=$sdkEscaped
"@

Set-Content -Path $localProps -Value $propsContent -Encoding UTF8
Write-Host "  Created local.properties -> $sdkPath" -ForegroundColor Green

# --- Step 4: Build ---
Write-Host ""
Write-Host "[4/4] Building debug APK..." -ForegroundColor Yellow
Write-Host ""

$env:ANDROID_HOME = $sdkPath

# Clear stale configuration cache (prevents old plugin versions from sticking)
$cacheDir = Join-Path $PSScriptRoot ".gradle\configuration-cache"
if (Test-Path $cacheDir) {
    Remove-Item -Recurse -Force $cacheDir -ErrorAction SilentlyContinue
    Write-Host "  Cleared stale configuration cache" -ForegroundColor DarkGray
}

# Clear Gradle user-home plugin resolution cache (fixes stale KSP version)
$pluginCache = Join-Path $env:USERPROFILE ".gradle\caches\modules-2\files-2.1\com.google.devtools.ksp"
if (Test-Path $pluginCache) {
    Remove-Item -Recurse -Force $pluginCache -ErrorAction SilentlyContinue
    Write-Host "  Cleared stale KSP plugin cache" -ForegroundColor DarkGray
}
$pluginMarker = Join-Path $env:USERPROFILE ".gradle\caches\modules-2\metadata-2.106\descriptors\com.google.devtools.ksp"
if (Test-Path $pluginMarker) {
    Remove-Item -Recurse -Force $pluginMarker -ErrorAction SilentlyContinue
}

$gradlew = Join-Path $PSScriptRoot "gradlew.bat"

if (-not (Test-Path $gradlew)) {
    $gradlew = Join-Path $PSScriptRoot "gradlew"
}

$ErrorActionPreference = "Continue"

& $gradlew :app:assembleDebug --no-daemon --no-configuration-cache --refresh-dependencies --console=plain
$buildExitCode = $LASTEXITCODE

$ErrorActionPreference = "Stop"

if ($buildExitCode -eq 0) {
    Write-Host ""
    Write-Host "  ========================================" -ForegroundColor Green
    Write-Host "     BUILD SUCCESSFUL!" -ForegroundColor Green
    Write-Host "  ========================================" -ForegroundColor Green
    Write-Host ""

    $apkPath = Join-Path $PSScriptRoot "app\build\outputs\apk\debug\app-debug.apk"
    if (Test-Path $apkPath) {
        Write-Host "  APK: $apkPath" -ForegroundColor Green
        Write-Host ""

        # Check if a device is connected
        $adbPath = Join-Path $sdkPath "platform-tools\adb.exe"
        if (Test-Path $adbPath) {
            $devices = & $adbPath devices 2>&1 | Select-String "device$"
            if ($devices) {
                Write-Host "  Device detected! Install now? (Y/n)" -ForegroundColor Cyan
                $answer = Read-Host
                if ($answer -ne "n" -and $answer -ne "N") {
                    Write-Host "  Installing..." -ForegroundColor Yellow
                    & $adbPath install -r $apkPath
                    Write-Host "  Installed! Launching Pixelfy..." -ForegroundColor Green
                    & $adbPath shell am start -n ai.pixelforge.enhancer/.MainActivity
                }
            } else {
                Write-Host "  Tip: Connect a phone with USB debugging to install directly." -ForegroundColor DarkGray
                Write-Host "       adb install $apkPath" -ForegroundColor DarkGray
            }
        }
    }
} else {
    Write-Host ""
    Write-Host "  BUILD FAILED" -ForegroundColor Red
    Write-Host "  Check the error messages above for details." -ForegroundColor Red
    Write-Host "  Re-run with: & $gradlew :app:assembleDebug --stacktrace" -ForegroundColor DarkGray
    exit 1
}
